variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_OPTS_EXTRA: ""
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_SERVER_ID: ""
  MAVEN_REPO_USER: ""
  MAVEN_REPO_PASS: ""
  SNAPSHOT_REPOSITORY_URL: ""
  SNAPSHOT_REPOSITORY_NAME: ""

# This template uses jdk8 for verifying and deploying images
image: maven:3.6.3-jdk-11

stages:
  - build
  - test
  - deploy

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - 'mvn -s .gitlab/settings.xml $MAVEN_CLI_OPTS $MAVEN_OPTS_EXTRA compile'

test:
  stage: test
  script:
    - 'mvn -s .gitlab/settings.xml $MAVEN_CLI_OPTS $MAVEN_OPTS_EXTRA test'

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS_EXTRA -s .gitlab/settings.xml
      package org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy
      -Dsnapshot.repository-id=${MAVEN_SERVER_ID}
      -Dsnapshot.repository-url=${SNAPSHOT_REPOSITORY_URL}
      -Dsnapshot.repository-name="${SNAPSHOT_REPOSITORY_NAME}"
      -DaltSnapshotDeploymentRepository="${MAVEN_SERVER_ID}::${SNAPSHOT_REPOSITORY_URL}"

